name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run lint
        run: |
          make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc vim-common openssl perl python3 python3-pip python3-pycryptodome
      - name: Run unsigned tests
        if: github.event_name == 'push'
        run: |
          UNSIGNED_TEST=1 make check

      - name: Run signed tests
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
        env:
          CORE_FLOW_FIXTURE_HMAC_KEY_B64: ${{ secrets.CORE_FLOW_FIXTURE_HMAC_KEY_B64 }}
          CORE_FLOW_FIXTURE_HMAC_B64: ${{ secrets.CORE_FLOW_FIXTURE_HMAC_B64 }}
          KECCAK_VECTOR_SIG_B64: ${{ secrets.KECCAK_VECTOR_SIG_B64 }}
          SECP256K1_VECTOR_SIG_B64: ${{ secrets.SECP256K1_VECTOR_SIG_B64 }}
          SIGNED_TEST: "1"
        run: |
          make check

      - name: Run unsigned tests (fork PR)
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true
        run: |
          UNSIGNED_TEST=1 make check
